import Head from 'next/head'
import { Fragment } from 'react'
import Carousel from '@/components/Home/Carousel'
import Brends from '@/components/Home/Brends'
import { Box } from '@mui/material'
import Products from '@/components/Home/Products'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pc Store</title>
        <meta name='description' content='Generated by Mirzamurod' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Fragment>
        <Box id='home' sx={{ mt: '-36px' }}>
          <Carousel />
          <Brends />
        </Box>
        <Products />
      </Fragment>
    </>
  )
}

Home.guestGuard = true
