import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()

  console.log(router.isReady)

  return (
    <>
      <Head>
        <title>Pc Store</title>
        <meta name='description' content='Generated by Mirzamurod' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>Hello World</main>
    </>
  )
}
